import type { Scenario } from "./scenario-engine.ts";
export const scenarios: Scenario[] = [
  {
    id: "prisoners-dilemma",
    type: "matrix",
    title: "Prisoner's Dilemma",
    category: "Classic",
    concept: "Dominant Strategy",
    situation:
      "The police question you separately. If both stay silent, each gets 1 year. If only one confesses, the betrayer goes free and the silent prisoner gets 5 years. If both confess, each gets 3 years.",
    opponent: "Partner",
    rows: ["Silent", "Confess"],
    cols: ["Silent", "Confess"],
    payoffs: [
      [1, 1],
      [5, 0],
      [0, 5],
      [3, 3],
    ],
    prison: true,
  },
  {
    id: "stag-hunt",
    type: "matrix",
    title: "Stag Hunt",
    category: "Classic",
    concept: "Coordination Game",
    situation:
      "Two hunters can each chase a stag (requires both) or a hare (can be caught alone). A stag feeds both for a week; a hare feeds only the hunter who caught it.",
    opponent: "Other Hunter",
    rows: ["Hunt Stag", "Hunt Hare"],
    cols: ["Hunt Stag", "Hunt Hare"],
    payoffs: [
      [4, 4],
      [0, 2],
      [2, 0],
      [2, 2],
    ],
  },
  {
    id: "battle-of-the-sexes",
    type: "matrix",
    title: "Battle of the Sexes",
    category: "Classic",
    concept: "Coordination with Conflict",
    situation:
      "You want to spend the evening together but disagree on venue. You prefer the boxing match; your partner prefers the ballet. Being together matters more than the venue, but each of you prefers your favorite when together.",
    opponent: "Partner",
    rows: ["Boxing", "Ballet"],
    cols: ["Boxing", "Ballet"],
    payoffs: [
      [3, 2],
      [0, 0],
      [0, 0],
      [2, 3],
    ],
  },
  {
    id: "hawk-dove",
    type: "matrix",
    title: "Hawk-Dove",
    category: "Classic",
    concept: "Evolutionary Stability",
    situation:
      "Two animals compete for a resource worth V=4. A Hawk always fights; a Dove always retreats when Hawk attacks. Fighting costs C=6 if both are Hawks. Doves split the resource when both are Doves.",
    opponent: "Rival",
    rows: ["Hawk", "Dove"],
    cols: ["Hawk", "Dove"],
    payoffs: [
      [0, 0],
      [4, 0],
      [0, 4],
      [2, 2],
    ],
  },
  {
    id: "matching-pennies",
    type: "matrix",
    title: "Matching Pennies",
    category: "Classic",
    concept: "Zero-Sum / Mixed Strategy",
    situation:
      "Each player secretly places a penny heads or tails up. If they match, Player A wins both; if they differ, Player B wins both. A pure coordination game in reverse — you want to be unpredictable.",
    opponent: "Player B",
    rows: ["Heads", "Tails"],
    cols: ["Heads", "Tails"],
    payoffs: [
      [1, 0],
      [0, 1],
      [0, 1],
      [1, 0],
    ],
  },
  {
    id: "deadlock",
    type: "matrix",
    title: "Deadlock",
    category: "Classic",
    concept: "Coordination Failure",
    situation:
      "Two countries decide whether to maintain free trade or impose protectionist tariffs. Mutual free trade benefits both most. But if one defects unilaterally while the other cooperates, the defector gains a short-term advantage. If both defect, trade shrinks and both lose. The challenge: both a cooperative and a protectionist equilibrium are self-sustaining.",
    opponent: "Country B",
    rows: ["Cooperate", "Defect"],
    cols: ["Cooperate", "Defect"],
    payoffs: [
      [3, 3],
      [0, 2],
      [2, 0],
      [1, 1],
    ],
  },
  {
    id: "chicken-game",
    type: "matrix",
    title: "Chicken Game",
    category: "Classic",
    concept: "Anti-Coordination",
    situation:
      "Two drivers race toward each other. Swerving is 'chicken.' Neither wants to swerve, but a head-on crash is worst of all. The one who swerves loses face; the one who holds loses everything if both hold.",
    opponent: "Other Driver",
    rows: ["Swerve", "Hold"],
    cols: ["Swerve", "Hold"],
    payoffs: [
      [2, 2],
      [1, 4],
      [4, 1],
      [0, 0],
    ],
  },
  {
    id: "assurance-game",
    type: "matrix",
    title: "Assurance Game",
    category: "Classic",
    concept: "Trust and Assurance",
    situation:
      "Two startups can build compatible software standards or go proprietary. If both build open standards, the market grows and both win big. If both go proprietary, they fragment the market. If one goes open while the other goes proprietary, the open one loses.",
    opponent: "Rival Startup",
    rows: ["Open Standard", "Proprietary"],
    cols: ["Open Standard", "Proprietary"],
    payoffs: [
      [4, 4],
      [1, 3],
      [3, 1],
      [2, 2],
    ],
  },
  {
    id: "pure-coordination",
    type: "matrix",
    title: "Pure Coordination",
    category: "Classic",
    concept: "Focal Points",
    situation:
      "You and a friend are separated in a city and must meet without communicating. You each independently choose a landmark. If you pick the same one, you meet. If not, you wander alone.",
    opponent: "Friend",
    rows: ["Central Station", "City Hall"],
    cols: ["Central Station", "City Hall"],
    payoffs: [
      [5, 5],
      [0, 0],
      [0, 0],
      [5, 5],
    ],
  },
  {
    id: "trust-game-matrix-form",
    type: "matrix",
    title: "Trust Game (Matrix Form)",
    category: "Classic",
    concept: "Trust and Reciprocity",
    situation:
      "An investor can Trust (send money to a trustee) or Not Trust. The trustee can Honor or Exploit. Trust creates surplus; exploitation destroys the relationship. In matrix form, both move simultaneously.",
    opponent: "Trustee",
    rows: ["Trust", "Don't Trust"],
    cols: ["Honor", "Exploit"],
    payoffs: [
      [4, 4],
      [0, 5],
      [2, 2],
      [2, 2],
    ],
  },
  {
    id: "entry-deterrence",
    type: "matrix",
    title: "Entry Deterrence",
    category: "Classic",
    concept: "Commitment and Threats",
    situation:
      "An incumbent firm threatens to fight any new entrant with a price war. An entrant must decide whether to enter the market. The incumbent must decide whether to actually fight or accommodate.",
    opponent: "Incumbent",
    rows: ["Enter", "Stay Out"],
    cols: ["Fight", "Accommodate"],
    payoffs: [
      [1, 1],
      [3, 3],
      [2, 4],
      [2, 4],
    ],
  },
  {
    id: "public-goods-dilemma",
    type: "matrix",
    title: "Public Goods Dilemma",
    category: "Classic",
    concept: "Free Rider Problem",
    situation:
      "Two neighbors decide whether to contribute to a shared garden. The garden benefits both regardless of who paid. Contributing costs you effort; free-riding is tempting since the other person's contribution benefits you anyway.",
    opponent: "Neighbor",
    rows: ["Contribute", "Free Ride"],
    cols: ["Contribute", "Free Ride"],
    payoffs: [
      [3, 3],
      [1, 4],
      [4, 1],
      [0, 0],
    ],
  },
  {
    id: "volunteers-dilemma",
    type: "matrix",
    title: "Volunteer's Dilemma",
    category: "Classic",
    concept: "Diffusion of Responsibility",
    situation:
      "A dangerous situation requires one person to volunteer (at personal cost) for the group to benefit. Everyone hopes someone else will step up. If nobody volunteers, everyone suffers.",
    opponent: "Other Person",
    rows: ["Volunteer", "Wait"],
    cols: ["Volunteer", "Wait"],
    payoffs: [
      [2, 3],
      [2, 3],
      [3, 2],
      [0, 0],
    ],
  },
  {
    id: "evolutionarily-stable-defection",
    type: "matrix",
    title: "Evolutionarily Stable Defection",
    category: "Classic",
    concept: "Evolutionary Game Theory",
    situation:
      "In a biological population, organisms play either Cooperator or Defector strategies. Cooperators benefit the group at personal cost; Defectors take without giving. Payoffs represent reproductive fitness.",
    opponent: "Random Opponent",
    rows: ["Cooperator", "Defector"],
    cols: ["Cooperator", "Defector"],
    payoffs: [
      [3, 3],
      [0, 4],
      [4, 0],
      [1, 1],
    ],
  },
  {
    id: "arms-race",
    type: "matrix",
    title: "Arms Race",
    category: "Classic",
    concept: "Security Dilemma",
    situation:
      "Two rival nations each decide whether to increase military spending. Both would prefer mutual restraint, but neither can afford to be the only one who disarms. Building up feels safer regardless of what the other does.",
    opponent: "Rival Nation",
    rows: ["Build Up", "Restrain"],
    cols: ["Build Up", "Restrain"],
    payoffs: [
      [1, 1],
      [4, 0],
      [0, 4],
      [3, 3],
    ],
  },
  {
    id: "price-war",
    type: "matrix",
    title: "Price War",
    category: "Business",
    concept: "Bertrand Competition",
    situation:
      "Two competing airlines set fares for the same route. Both can charge high or cut to low fares. If both cut, margins collapse. If both hold high, profits are fat. But the one who cuts while the other holds steals the whole market.",
    opponent: "Rival Airline",
    rows: ["High Fare", "Cut Fare"],
    cols: ["High Fare", "Cut Fare"],
    payoffs: [
      [4, 4],
      [0, 5],
      [5, 0],
      [1, 1],
    ],
  },
  {
    id: "product-launch-timing",
    type: "matrix",
    title: "Product Launch Timing",
    category: "Business",
    concept: "First Mover vs. Fast Follower",
    situation:
      "Two tech companies are racing to launch a product. Launching early captures the market but risks shipping bugs. Waiting lets you polish the product but cedes first-mover advantage if the rival launches first.",
    opponent: "Rival Firm",
    rows: ["Launch Now", "Wait"],
    cols: ["Launch Now", "Wait"],
    payoffs: [
      [2, 2],
      [4, 1],
      [1, 4],
      [3, 3],
    ],
  },
  {
    id: "r-d-investment-race",
    type: "matrix",
    title: "R&D Investment Race",
    category: "Business",
    concept: "Patent Race",
    situation:
      "Two pharmaceutical firms decide whether to invest heavily in R&D for a new drug. The first to patent wins the market exclusively. But heavy R&D spending is costly, and only one can win the patent.",
    opponent: "Rival Pharma",
    rows: ["Invest Heavily", "Invest Moderately"],
    cols: ["Invest Heavily", "Invest Moderately"],
    payoffs: [
      [1, 0],
      [2, 1],
      [0, 2],
      [2, 2],
    ],
  },
  {
    id: "ad-spending-war",
    type: "matrix",
    title: "Ad Spending War",
    category: "Business",
    concept: "Advertising as Prisoner's Dilemma",
    situation:
      "Two consumer goods companies decide how much to spend on advertising. Heavy advertising by both cancels out — market shares stay the same but costs are higher. Yet each fears losing share if the other advertises while they don't.",
    opponent: "Rival Brand",
    rows: ["Advertise Heavily", "Advertise Lightly"],
    cols: ["Advertise Heavily", "Advertise Lightly"],
    payoffs: [
      [2, 2],
      [4, 0],
      [0, 4],
      [3, 3],
    ],
  },
  {
    id: "negotiation-anchoring",
    type: "matrix",
    title: "Negotiation: Anchoring",
    category: "Business",
    concept: "Bargaining and First Offers",
    situation:
      "You and a supplier negotiate on price. You can anchor high (aggressive opening) or anchor moderate (cooperative signal). The supplier can counter low or counter moderate. The outcome depends on both anchoring strategies.",
    opponent: "Supplier",
    rows: ["Anchor High", "Anchor Moderate"],
    cols: ["Counter Low", "Counter Moderate"],
    payoffs: [
      [2, 3],
      [4, 1],
      [1, 4],
      [3, 3],
    ],
  },
  {
    id: "merger-vs-compete",
    type: "matrix",
    title: "Merger vs. Compete",
    category: "Business",
    concept: "Horizontal Integration",
    situation:
      "Two regional banks consider merging or staying independent and competing aggressively. A merger creates scale efficiencies but faces regulatory scrutiny. Competition erodes margins. Both together would dominate, but the merger takes time and political capital.",
    opponent: "Rival Bank",
    rows: ["Merge", "Compete"],
    cols: ["Merge", "Compete"],
    payoffs: [
      [4, 4],
      [1, 3],
      [3, 1],
      [2, 2],
    ],
  },
  {
    id: "platform-compatibility",
    type: "matrix",
    title: "Platform Compatibility",
    category: "Business",
    concept: "Network Effects",
    situation:
      "Two software companies each choose whether to make their platforms compatible or walled-garden proprietary. Compatibility grows the overall market; proprietary locks in customers. If one opens and the other walls, the open platform often loses users to the closed one that benefits from both.",
    opponent: "Rival Platform",
    rows: ["Open/Compatible", "Proprietary"],
    cols: ["Open/Compatible", "Proprietary"],
    payoffs: [
      [4, 4],
      [1, 4],
      [4, 1],
      [2, 2],
    ],
  },
  {
    id: "labor-negotiation",
    type: "matrix",
    title: "Labor Negotiation",
    category: "Business",
    concept: "Bargaining Power",
    situation:
      "Management and union each choose a stance: Hard Line (demand maximum) or Flexible (compromise). If both go hard line, talks break down and a strike happens. If both are flexible, a deal gets made. Asymmetric stances favor the harder party.",
    opponent: "Union/Management",
    rows: ["Hard Line", "Flexible"],
    cols: ["Hard Line", "Flexible"],
    payoffs: [
      [0, 0],
      [2, 3],
      [3, 2],
      [3, 3],
    ],
  },
  {
    id: "market-entry-niche-vs-mass",
    type: "matrix",
    title: "Market Entry: Niche vs. Mass",
    category: "Business",
    concept: "Product Differentiation",
    situation:
      "Two new consumer goods companies each choose to target the niche premium market or the mass market. The mass market is bigger but more crowded; the niche rewards differentiation. Same-segment competition is destructive.",
    opponent: "Rival Brand",
    rows: ["Niche Premium", "Mass Market"],
    cols: ["Niche Premium", "Mass Market"],
    payoffs: [
      [1, 1],
      [4, 3],
      [3, 4],
      [2, 2],
    ],
  },
  {
    id: "supply-chain-make-or-buy",
    type: "matrix",
    title: "Supply Chain: Make or Buy",
    category: "Business",
    concept: "Vertical Integration",
    situation:
      "Two companies in the same supply chain each decide whether to vertically integrate (make the component themselves) or outsource to each other. If both integrate, they duplicate capabilities. If both outsource, nobody makes the component.",
    opponent: "Supply Chain Partner",
    rows: ["Integrate (Make)", "Outsource (Buy)"],
    cols: ["Integrate (Make)", "Outsource (Buy)"],
    payoffs: [
      [2, 2],
      [4, 3],
      [3, 4],
      [0, 0],
    ],
  },
  {
    id: "innovation-open-source-vs-proprietary",
    type: "matrix",
    title: "Innovation: Open Source vs. Proprietary",
    category: "Business",
    concept: "IP Strategy",
    situation:
      "A tech company decides whether to open-source its core technology or keep it proprietary. A potential partner makes the same choice. Open-sourcing builds ecosystem but surrenders control; proprietary protects margins but limits adoption.",
    opponent: "Tech Partner",
    rows: ["Open Source", "Proprietary"],
    cols: ["Open Source", "Proprietary"],
    payoffs: [
      [4, 4],
      [2, 3],
      [3, 2],
      [2, 2],
    ],
  },
  {
    id: "bidding-on-contract",
    type: "matrix",
    title: "Bidding on Contract",
    category: "Business",
    concept: "Common Value Auction",
    situation:
      "You and a rival firm are bidding on a government contract. You can bid aggressively (low price, thin margin) or bid conservatively (higher price, better margin). Lowest bid wins the whole contract. Both bidding conservatively implies implicit coordination.",
    opponent: "Rival Firm",
    rows: ["Bid Aggressively", "Bid Conservatively"],
    cols: ["Bid Aggressively", "Bid Conservatively"],
    payoffs: [
      [1, 1],
      [2, 0],
      [0, 2],
      [3, 3],
    ],
  },
  {
    id: "talent-poaching",
    type: "matrix",
    title: "Talent Poaching",
    category: "Business",
    concept: "Tournament Theory",
    situation:
      "Two tech firms both raid each other's engineers with aggressive offers. If one recruits hard while the other doesn't, they win top talent. If both recruit aggressively, they cancel out and only raise the market wage floor.",
    opponent: "Rival Firm",
    rows: ["Recruit Aggressively", "Restrain"],
    cols: ["Recruit Aggressively", "Restrain"],
    payoffs: [
      [2, 2],
      [4, 1],
      [1, 4],
      [3, 3],
    ],
  },
  {
    id: "retail-location-cluster-or-spread",
    type: "matrix",
    title: "Retail Location: Cluster or Spread",
    category: "Business",
    concept: "Hotelling's Spatial Competition",
    situation:
      "Two coffee shops choose locations in a city. Both can cluster downtown (max foot traffic, but split customers) or spread out (capture separate neighborhoods with less competition). Hotelling's principle applies.",
    opponent: "Rival Coffee Shop",
    rows: ["Cluster Downtown", "Spread Out"],
    cols: ["Cluster Downtown", "Spread Out"],
    payoffs: [
      [2, 2],
      [3, 3],
      [3, 3],
      [2, 2],
    ],
  },
  {
    id: "esg-disclosure",
    type: "matrix",
    title: "ESG Disclosure",
    category: "Business",
    concept: "Signaling and Credibility",
    situation:
      "Two publicly traded competitors both consider voluntary ESG disclosures beyond legal requirements. Early, detailed disclosure builds trust with investors but reveals competitive information. If one discloses and the other doesn't, the non-discloser captures the opaqueness benefit while looking no worse.",
    opponent: "Rival Corp",
    rows: ["Disclose Fully", "Minimal Disclosure"],
    cols: ["Disclose Fully", "Minimal Disclosure"],
    payoffs: [
      [3, 3],
      [1, 4],
      [4, 1],
      [2, 2],
    ],
  },
  {
    id: "tragedy-of-the-commons",
    type: "matrix",
    title: "Tragedy of the Commons",
    category: "Social Dilemmas",
    concept: "Common Resource Extraction",
    situation:
      "Two fishing crews share the same fishing ground. Each decides to fish at sustainable or maximum rates. The fish population can only sustain so much harvest. If both over-fish, the stock degrades and yields fall — but not immediately to zero.",
    opponent: "Other Crew",
    rows: ["Sustainable", "Maximum Harvest"],
    cols: ["Sustainable", "Maximum Harvest"],
    payoffs: [
      [4, 4],
      [1, 5],
      [5, 1],
      [2, 2],
    ],
  },
  {
    id: "climate-commitment",
    type: "matrix",
    title: "Climate Commitment",
    category: "Social Dilemmas",
    concept: "Global Public Goods",
    situation:
      "Two large economies decide whether to commit to costly emissions reductions. Clean air is a global public good — even a non-reducer benefits from the other's sacrifice. Reducing is expensive; not reducing and letting the other carry the cost is tempting.",
    opponent: "Other Economy",
    rows: ["Reduce Emissions", "Free Ride"],
    cols: ["Reduce Emissions", "Free Ride"],
    payoffs: [
      [4, 4],
      [1, 5],
      [5, 1],
      [2, 2],
    ],
  },
  {
    id: "recycling-and-social-norms",
    type: "matrix",
    title: "Recycling and Social Norms",
    category: "Social Dilemmas",
    concept: "Social Norms and Compliance",
    situation:
      "You and your neighbor decide whether to sort recycling properly (costly effort) or bin everything together (lazy but cheaper). The recycling program works only if enough people participate. Social shame and environmental benefit are in play.",
    opponent: "Neighbor",
    rows: ["Sort Properly", "Bin Everything"],
    cols: ["Sort Properly", "Bin Everything"],
    payoffs: [
      [4, 4],
      [1, 3],
      [3, 1],
      [2, 2],
    ],
  },
  {
    id: "vaccine-hesitancy",
    type: "matrix",
    title: "Vaccine Hesitancy",
    category: "Social Dilemmas",
    concept: "Herd Immunity Free Riding",
    situation:
      "You decide whether to vaccinate. If enough others vaccinate, herd immunity protects even the unvaccinated. Vaccination has small personal risk; free-riding works until vaccination rates drop below threshold and outbreaks return.",
    opponent: "Community Member",
    rows: ["Vaccinate", "Don't Vaccinate"],
    cols: ["Vaccinate", "Don't Vaccinate"],
    payoffs: [
      [3, 3],
      [2, 4],
      [4, 2],
      [0, 0],
    ],
  },
  {
    id: "noise-complaint",
    type: "matrix",
    title: "Noise Complaint",
    category: "Social Dilemmas",
    concept: "Coase Theorem",
    situation:
      "Two apartment neighbors decide whether to keep noise down after 10pm. Each values quiet sleep and the ability to host parties. The Coase Theorem says they could negotiate efficiently — but transaction costs and spite get in the way.",
    opponent: "Neighbor",
    rows: ["Keep Quiet", "Make Noise"],
    cols: ["Keep Quiet", "Make Noise"],
    payoffs: [
      [4, 4],
      [1, 3],
      [3, 1],
      [2, 2],
    ],
  },
  {
    id: "tipping-culture",
    type: "matrix",
    title: "Tipping Culture",
    category: "Social Dilemmas",
    concept: "Conventions and Reciprocity",
    situation:
      "You're at a restaurant. You can tip generously (social norm upheld) or tip nothing (save money). If everyone tips, servers earn livable wages and service quality stays high. If tipping collapses as a norm, the whole system shifts.",
    opponent: "Other Diner",
    rows: ["Tip Generously", "Don't Tip"],
    cols: ["Tip Generously", "Don't Tip"],
    payoffs: [
      [3, 3],
      [1, 2],
      [2, 1],
      [2, 2],
    ],
  },
  {
    id: "mask-wearing-externality",
    type: "matrix",
    title: "Mask-Wearing Externality",
    category: "Social Dilemmas",
    concept: "Negative Externality",
    situation:
      "During flu season, each person chooses whether to wear a mask. Masks protect others more than the wearer. If everyone masks, transmission drops significantly. Individual benefit is low; collective benefit is high.",
    opponent: "Commuter",
    rows: ["Mask Up", "No Mask"],
    cols: ["Mask Up", "No Mask"],
    payoffs: [
      [3, 3],
      [1, 4],
      [4, 1],
      [2, 2],
    ],
  },
  {
    id: "data-privacy-sharing",
    type: "matrix",
    title: "Data Privacy Sharing",
    category: "Social Dilemmas",
    concept: "Information Commons",
    situation:
      "Two hospitals decide whether to share anonymized patient data for medical research. Sharing contributes to collective knowledge but risks patient trust. If neither shares, research stalls. If both share, breakthroughs happen faster.",
    opponent: "Rival Hospital",
    rows: ["Share Data", "Withhold"],
    cols: ["Share Data", "Withhold"],
    payoffs: [
      [4, 4],
      [1, 3],
      [3, 1],
      [2, 2],
    ],
  },
  {
    id: "nuclear-deterrence",
    type: "matrix",
    title: "Nuclear Deterrence",
    category: "Int'l Relations",
    concept: "Mutual Assured Destruction",
    situation:
      "Two nuclear powers each decide whether to launch a first strike or maintain deterrence. If neither strikes, peace holds. If both strike, civilization ends. If one strikes first, that nation might gain advantage — but triggers retaliation.",
    opponent: "Rival Power",
    rows: ["Maintain Deterrence", "First Strike"],
    cols: ["Maintain Deterrence", "First Strike"],
    payoffs: [
      [4, 4],
      [0, 3],
      [3, 0],
      [0, 0],
    ],
  },
  {
    id: "trade-war-escalation",
    type: "matrix",
    title: "Trade War Escalation",
    category: "Int'l Relations",
    concept: "Tariff Retaliation",
    situation:
      "Two trading nations each decide whether to impose tariffs or maintain free trade. Tariffs protect domestic industries at the cost of higher prices and retaliatory tariffs. Free trade maximizes efficiency but leaves import-competing industries exposed.",
    opponent: "Trade Partner",
    rows: ["Free Trade", "Impose Tariffs"],
    cols: ["Free Trade", "Impose Tariffs"],
    payoffs: [
      [4, 4],
      [1, 5],
      [5, 1],
      [2, 2],
    ],
  },
  {
    id: "sanctions-regime",
    type: "matrix",
    title: "Sanctions Regime",
    category: "Int'l Relations",
    concept: "Coalition Maintenance",
    situation:
      "Two allied countries decide whether to maintain economic sanctions on a third country or defect for economic gain. Sanctions only work if the coalition holds. Each ally is tempted by lucrative trade with the sanctioned party.",
    opponent: "Allied Country",
    rows: ["Hold Sanctions", "Defect"],
    cols: ["Hold Sanctions", "Defect"],
    payoffs: [
      [3, 3],
      [0, 4],
      [4, 0],
      [1, 1],
    ],
  },
  {
    id: "cyber-espionage-norms",
    type: "matrix",
    title: "Cyber Espionage Norms",
    category: "Int'l Relations",
    concept: "Emerging Norms",
    situation:
      "Two cyber powers each decide whether to restrain state-sponsored hacking to critical infrastructure or conduct unrestricted cyber operations. Both benefit from global digital stability; both are tempted by intelligence advantages.",
    opponent: "Rival State",
    rows: ["Show Restraint", "Hack Freely"],
    cols: ["Show Restraint", "Hack Freely"],
    payoffs: [
      [4, 4],
      [1, 5],
      [5, 1],
      [2, 2],
    ],
  },
  {
    id: "foreign-aid-strategy",
    type: "matrix",
    title: "Foreign Aid Strategy",
    category: "Int'l Relations",
    concept: "Conditionality",
    situation:
      "A donor country and a recipient government each choose whether to attach conditions (governance reforms, anti-corruption measures) or give/accept unconditionally. Conditionality can improve outcomes but is often ignored once money flows.",
    opponent: "Recipient Gov't",
    rows: ["Conditional Aid", "Unconditional Aid"],
    cols: ["Reform", "Don't Reform"],
    payoffs: [
      [4, 3],
      [1, 1],
      [3, 2],
      [2, 4],
    ],
  },
  {
    id: "algorithm-transparency",
    type: "matrix",
    title: "Algorithm Transparency",
    category: "Tech & Digital",
    concept: "Accountability vs. IP",
    situation:
      "Two social media platforms decide whether to publish their recommendation algorithm for public audit. Transparency builds trust and reduces regulatory risk; secrecy protects proprietary advantage. If one opens and the other doesn't, the open one loses IP while the other gains credibility by association.",
    opponent: "Rival Platform",
    rows: ["Publish Algorithm", "Keep Secret"],
    cols: ["Publish Algorithm", "Keep Secret"],
    payoffs: [
      [4, 4],
      [1, 2],
      [2, 1],
      [3, 3],
    ],
  },
  {
    id: "content-moderation-standard",
    type: "matrix",
    title: "Content Moderation Standard",
    category: "Tech & Digital",
    concept: "Platform Governance",
    situation:
      "Two competing video platforms set moderation standards — strict (removes more content, loses some creators) or lenient (keeps more content, attracts creators but risks advertiser pullback). If both are strict, advertisers are happy; if both are lenient, creators flock to both equally.",
    opponent: "Rival Platform",
    rows: ["Strict Moderation", "Lenient Moderation"],
    cols: ["Strict Moderation", "Lenient Moderation"],
    payoffs: [
      [3, 3],
      [1, 4],
      [4, 1],
      [2, 2],
    ],
  },
  {
    id: "startup-vs-incumbent-api-access",
    type: "matrix",
    title: "Startup vs. Incumbent: API Access",
    category: "Tech & Digital",
    concept: "Platform Power",
    situation:
      "A dominant platform can open its API to startups or restrict it. Startups can build on the platform or build a rival. Open APIs help the ecosystem but risk enabling future rivals. Building a rival is costly but preserves independence.",
    opponent: "Platform",
    rows: ["Build on Platform", "Build Rival"],
    cols: ["Open API", "Restrict API"],
    payoffs: [
      [4, 3],
      [2, 2],
      [1, 1],
      [3, 2],
    ],
  },
  {
    id: "ai-safety-investment",
    type: "matrix",
    title: "AI Safety Investment",
    category: "Tech & Digital",
    concept: "Safety vs. Speed Race",
    situation:
      "Two AI labs decide whether to invest heavily in safety research before deploying powerful models, or race to deploy faster with lighter safety checks. If both invest in safety, the field advances responsibly. If one races while the other is careful, the racer gains market share.",
    opponent: "Rival AI Lab",
    rows: ["Invest in Safety", "Race to Deploy"],
    cols: ["Invest in Safety", "Race to Deploy"],
    payoffs: [
      [4, 4],
      [1, 5],
      [5, 1],
      [2, 2],
    ],
  },
  {
    id: "salary-negotiation",
    type: "ultimatum",
    title: "Salary Negotiation",
    category: "Ultimatum",
    concept: "Fairness and BATNA",
    situation:
      "You're negotiating your starting salary. HR has offered you 60. You can propose your counter between 10-90 (as a share of a 100-point budget). HR has a hidden reservation — below a certain offer to them, they withdraw and hire another candidate.",
    opponent: "HR Manager",
    threshold: 30,
  },
  {
    id: "divorce-settlement",
    type: "ultimatum",
    title: "Divorce Settlement",
    category: "Ultimatum",
    concept: "Loss Aversion in Bargaining",
    situation:
      "Splitting joint assets in a divorce. You propose how to divide 100 points of marital property. Your spouse has a hidden minimum — below it, they'd rather litigate (both pay lawyers and get less) than accept your offer.",
    opponent: "Spouse",
    threshold: 40,
  },
  {
    id: "trust-between-partners",
    type: "centipede",
    title: "Trust Between Partners",
    category: "Centipede",
    concept: "Backward Induction vs. Trust",
    situation:
      "You and a business partner alternate decisions on a joint project. At each stage, you can take your share of the current pot or pass to let it grow. Compare taking now with passing control to your partner. Does trust change your choice?",
    opponent: "Partner",
    nodes: 12,
    startPot: [4, 1],
    growth: 1.6,
    computer: "cooperate",
  },
  {
    id: "first-price-procurement-bid",
    type: "matrix",
    title: "First-Price Procurement Bid",
    category: "Auctions",
    concept: "Bid Shading",
    situation:
      "You are bidding on a municipal procurement contract against one rival. Bid too low and you win with no margin; bid too high and you lose the job. You have to balance winning probability against profit.",
    opponent: "Rival Bidder",
    rows: ["Low Bid", "Balanced Bid", "Aggressive Bid"],
    cols: ["Low Bid", "Balanced Bid", "Aggressive Bid"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "english-auction-exit-point",
    type: "matrix",
    title: "English Auction Exit Point",
    category: "Auctions",
    concept: "Dropout Discipline",
    situation:
      "You are still in an English auction for a logistics warehouse. You can exit early, stay disciplined near your estimate, or chase the lot beyond fundamentals. The last bidder standing wins, but overpaying can destroy the deal.",
    opponent: "Other Bidder",
    rows: ["Exit Early", "Stay Disciplined", "Chase Late"],
    cols: ["Exit Early", "Stay Disciplined", "Chase Late"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "spectrum-auction-block",
    type: "matrix",
    title: "Spectrum Auction Block",
    category: "Auctions",
    concept: "Winner's Curse",
    situation:
      "You are bidding on a national spectrum block whose value depends on future subscriber growth. Conservative bids protect capital, informed bids reflect your base case, and aggressive bids assume the market will boom. If everyone gets too optimistic, the winner can regret the victory.",
    opponent: "Telecom Rival",
    rows: ["Conservative Bid", "Informed Bid", "Aggressive Bid"],
    cols: ["Conservative Bid", "Informed Bid", "Aggressive Bid"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "startup-acquisition-auction",
    type: "matrix",
    title: "Startup Acquisition Auction",
    category: "Auctions",
    concept: "Synergy Overestimation",
    situation:
      "You are bidding to acquire a startup that might fit your platform. A low offer preserves downside protection, a balanced offer reflects realistic synergies, and an aggressive offer assumes the integration will be perfect. The danger is paying for synergies that never arrive.",
    opponent: "Strategic Buyer",
    rows: ["Protective Offer", "Balanced Offer", "Stretch Offer"],
    cols: ["Protective Offer", "Balanced Offer", "Stretch Offer"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "rare-art-auction",
    type: "matrix",
    title: "Rare Art Auction",
    category: "Auctions",
    concept: "Private Value vs. Emotion",
    situation:
      "You are bidding on a rare painting that also carries prestige. You can bid with restraint, bid near your true willingness to pay, or let status take over. The emotional premium is real, but so is buyer's remorse.",
    opponent: "Collector",
    rows: ["Restrained Bid", "True-Value Bid", "Status Bid"],
    cols: ["Restrained Bid", "True-Value Bid", "Status Bid"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "timber-lease-auction",
    type: "matrix",
    title: "Timber Lease Auction",
    category: "Auctions",
    concept: "Common-Value Uncertainty",
    situation:
      "You are bidding on a timber lease with uncertain extraction quality. A cautious bid protects you if the forest disappoints, a calibrated bid reflects your expected value, and an aggressive bid assumes your survey is right. If your estimate is the highest because it is the noisiest, winning is dangerous.",
    opponent: "Forestry Firm",
    rows: ["Cautious Bid", "Calibrated Bid", "Bold Bid"],
    cols: ["Cautious Bid", "Calibrated Bid", "Bold Bid"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "prime-time-ad-slot-auction",
    type: "matrix",
    title: "Prime-Time Ad Slot Auction",
    category: "Auctions",
    concept: "Budget Constraints",
    situation:
      "You are bidding for a prime-time ad slot ahead of a product launch. Underbidding saves budget but risks missing the audience, while an all-out bid can blow your campaign economics. Your best move depends on how disciplined the other advertiser is.",
    opponent: "Brand Rival",
    rows: ["Budget Bid", "Target Bid", "All-Out Bid"],
    cols: ["Budget Bid", "Target Bid", "All-Out Bid"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "offshore-oil-block-auction",
    type: "matrix",
    title: "Offshore Oil Block Auction",
    category: "Auctions",
    concept: "Reserve Estimation",
    situation:
      "You are bidding on offshore drilling rights with incomplete geological data. A low offer preserves capital, a measured offer reflects your reserve model, and a very high offer assumes the upside case. The more uncertain the underlying asset, the more costly a heroic bid becomes.",
    opponent: "Energy Major",
    rows: ["Low Offer", "Measured Offer", "Heroic Offer"],
    cols: ["Low Offer", "Measured Offer", "Heroic Offer"],
    payoffs: [
      [4, 4],
      [0, 6],
      [0, 7],
      [6, 0],
      [5, 5],
      [2, 4],
      [7, 0],
      [4, 2],
      [1, 1],
    ],
  },
  {
    id: "discount-airline-fare-ladder",
    type: "matrix",
    title: "Discount Airline Fare Ladder",
    category: "Oligopoly",
    concept: "Bertrand Undercutting",
    situation:
      "You and a rival airline are setting fares for the same route. A premium fare preserves margin, a market fare matches the pack, and a slash fare tries to steal demand outright. Every fare cut pressures the other side to follow.",
    opponent: "Airline Rival",
    rows: ["Premium Fare", "Market Fare", "Slash Fare"],
    cols: ["Premium Fare", "Market Fare", "Slash Fare"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "three-tier-streaming-price-war",
    type: "matrix",
    title: "Three-Tier Streaming Price War",
    category: "Oligopoly",
    concept: "Price Dispersion",
    situation:
      "You are pricing a streaming subscription against a close rival. You can stay premium, match the middle of the market, or cut aggressively to grab share. Cheap prices attract users fast, but the margin damage is immediate.",
    opponent: "Streaming Rival",
    rows: ["Premium Price", "Middle Price", "Aggressive Cut"],
    cols: ["Premium Price", "Middle Price", "Aggressive Cut"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "semiconductor-capacity-choice",
    type: "matrix",
    title: "Semiconductor Capacity Choice",
    category: "Oligopoly",
    concept: "Cournot Quantity Competition",
    situation:
      "You are choosing how much chip capacity to commit before demand is fully known. Low capacity keeps utilization high, balanced capacity targets steady demand, and aggressive capacity bets on a boom. Too much output floods the market and crushes price.",
    opponent: "Chipmaker",
    rows: ["Low Capacity", "Balanced Capacity", "Aggressive Capacity"],
    cols: ["Low Capacity", "Balanced Capacity", "Aggressive Capacity"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "grocery-chain-price-leadership",
    type: "matrix",
    title: "Grocery Chain Price Leadership",
    category: "Oligopoly",
    concept: "Follow-the-Leader Pricing",
    situation:
      "You are deciding next week's headline price promotion. You can hold a premium line, match the market leader, or go hard-discount. The more aggressively anyone cuts, the more pressure the rest of the market feels to move with them.",
    opponent: "Competing Chain",
    rows: ["Hold Premium", "Match Leader", "Deep Discount"],
    cols: ["Hold Premium", "Match Leader", "Deep Discount"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "ride-hail-surge-discipline",
    type: "matrix",
    title: "Ride-Hail Surge Discipline",
    category: "Oligopoly",
    concept: "Dynamic Pricing Pressure",
    situation:
      "You are setting surge multipliers during a demand spike. A mild multiplier preserves goodwill, a balanced multiplier rations demand, and a steep multiplier monetizes the rush. If one platform goes softer than the other, drivers and riders rebalance quickly.",
    opponent: "Rival Platform",
    rows: ["Mild Surge", "Balanced Surge", "Steep Surge"],
    cols: ["Mild Surge", "Balanced Surge", "Steep Surge"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "ev-battery-output-race",
    type: "matrix",
    title: "EV Battery Output Race",
    category: "Oligopoly",
    concept: "Capacity Preemption",
    situation:
      "You and a rival are deciding battery output for the next model year. Conservative production protects margins, balanced output fits baseline forecasts, and aggressive output tries to lock in market share. Overbuilding, though, can turn scale into a glut.",
    opponent: "Battery Rival",
    rows: ["Conservative Output", "Balanced Output", "Aggressive Output"],
    cols: ["Conservative Output", "Balanced Output", "Aggressive Output"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "cement-producer-quota-temptation",
    type: "matrix",
    title: "Cement Producer Quota Temptation",
    category: "Oligopoly",
    concept: "Cartel Instability",
    situation:
      "You and another cement producer have an informal understanding to avoid flooding the market. You can stay tight on volume, produce the agreed amount, or quietly overship. Extra tons look attractive until everyone does it.",
    opponent: "Regional Producer",
    rows: ["Tight Quota", "Agreed Quota", "Overship"],
    cols: ["Tight Quota", "Agreed Quota", "Overship"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "cloud-storage-tiering",
    type: "matrix",
    title: "Cloud Storage Tiering",
    category: "Oligopoly",
    concept: "Versioning Strategy",
    situation:
      "You are choosing a storage pricing tier against a rival provider. A high-priced premium plan keeps margins rich, a balanced plan targets the core market, and a stripped-down bargain tier tries to lock in volume. Once one firm cheapens the market, the other is pulled after it.",
    opponent: "Cloud Rival",
    rows: ["Premium Tier", "Core Tier", "Bargain Tier"],
    cols: ["Premium Tier", "Core Tier", "Bargain Tier"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "landlord-rent-relief",
    type: "ultimatum",
    title: "Landlord Rent Relief",
    category: "Ultimatum",
    concept: "Power Asymmetry",
    situation:
      "Your tenant has fallen behind after an expensive move. You are offering a rent-relief split of 100 points between immediate payment and forgiveness, and you keep the remainder. The tenant will reject a proposal they read as one-sided, even though they need the apartment.",
    opponent: "Tenant",
    threshold: 38,
  },
  {
    id: "monopolist-refund-policy",
    type: "ultimatum",
    title: "Monopolist Refund Policy",
    category: "Ultimatum",
    concept: "Customer Fairness Norms",
    situation:
      "Your company lost a customer's data and you are deciding what refund split to offer from a 100-point compensation budget. You keep whatever is not refunded. The customer cannot force better terms, but can still reject the deal and escalate publicly.",
    opponent: "Customer",
    threshold: 42,
  },
  {
    id: "gig-platform-bonus-split",
    type: "ultimatum",
    title: "Gig Platform Bonus Split",
    category: "Ultimatum",
    concept: "Algorithmic Bargaining",
    situation:
      "A delivery platform is allocating a limited retention bonus and you are deciding the split between the platform and a driver. You keep the rest for the company, but the driver can reject and churn. The more automated the decision feels, the more salient fairness can become.",
    opponent: "Driver",
    threshold: 34,
  },
  {
    id: "emergency-shift-coverage",
    type: "ultimatum",
    title: "Emergency Shift Coverage",
    category: "Ultimatum",
    concept: "Time Pressure",
    situation:
      "A nurse agrees to cover an overnight emergency shift only if your proposed split of the overtime pool feels acceptable. You are the administrator proposing how much of 100 points they get. There is little time, but urgency does not eliminate fairness concerns.",
    opponent: "Nurse",
    threshold: 36,
  },
  {
    id: "used-car-buyback",
    type: "ultimatum",
    title: "Used Car Buyback",
    category: "Ultimatum",
    concept: "Outside Options",
    situation:
      "You are offering to buy back a defective used car from its owner. You propose how to split a 100-point settlement fund, and you keep the remainder for the dealership. The owner can reject and try arbitration instead.",
    opponent: "Car Owner",
    threshold: 40,
  },
  {
    id: "restaurant-tip-pool",
    type: "ultimatum",
    title: "Restaurant Tip Pool",
    category: "Ultimatum",
    concept: "Non-Monetary Stakes",
    situation:
      "You are the restaurant manager deciding how to split a 100-point discretionary tip pool with the closing server. You keep whatever is not allocated, but the server can reject and turn the issue into a staff-wide morale problem. Respect matters almost as much as the money.",
    opponent: "Server",
    threshold: 37,
  },
  {
    id: "startup-cofounder-exit",
    type: "ultimatum",
    title: "Startup Cofounder Exit",
    category: "Ultimatum",
    concept: "Relationship Preservation",
    situation:
      "A departing cofounder is leaving and you are proposing how to divide a 100-point exit package. You keep the remaining points for the continuing team. The cofounder can reject and turn a clean exit into an expensive fight.",
    opponent: "Departing Cofounder",
    threshold: 43,
  },
  {
    id: "family-inheritance-split",
    type: "ultimatum",
    title: "Family Inheritance Split",
    category: "Ultimatum",
    concept: "Cultural Fairness Norms",
    situation:
      "You are the executor proposing how to divide 100 points of inheritance with a sibling. You keep the rest for your own branch of the family. Legal control does not erase deeply held norms about what counts as a fair share.",
    opponent: "Sibling",
    threshold: 46,
  },
  {
    id: "anonymous-lab-bonus",
    type: "ultimatum",
    title: "Anonymous Lab Bonus",
    category: "Ultimatum",
    concept: "Anonymity Effects",
    situation:
      "You are allocating an unexpected lab bonus with a research assistant through an anonymous online form. You choose how many of 100 points they get and keep the rest. The assistant will never know it was you personally, only the offer itself.",
    opponent: "Research Assistant",
    threshold: 30,
  },
  {
    id: "job-market-credential-signal",
    type: "matrix",
    title: "Job Market Credential Signal",
    category: "Signaling",
    concept: "Education as Signal",
    situation:
      "You are applying for a competitive analyst role. You can show no extra credential, a targeted professional certificate, or an expensive prestige signal; the employer can reject, interview, or fast-track you. Your choice is partly about productivity and partly about what the employer infers from it.",
    opponent: "Employer",
    rows: ["No Extra Signal", "Targeted Certificate", "Prestige Signal"],
    cols: ["Reject", "Interview", "Fast-Track"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "insurance-deductible-signal",
    type: "matrix",
    title: "Insurance Deductible Signal",
    category: "Signaling",
    concept: "Adverse Selection",
    situation:
      "You are shopping for health insurance and can choose a low, medium, or high deductible plan. The insurer can decline, screen carefully, or quickly approve. Your plan choice signals what risk type you might be.",
    opponent: "Insurer",
    rows: ["Low Deductible", "Medium Deductible", "High Deductible"],
    cols: ["Decline", "Screen", "Approve Fast"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "luxury-warranty-signal",
    type: "matrix",
    title: "Luxury Warranty Signal",
    category: "Signaling",
    concept: "Quality Signaling",
    situation:
      "You are launching a premium appliance and can offer no warranty, a standard warranty, or an unusually strong warranty. Buyers can ignore the signal, investigate, or purchase immediately. Strong warranties are only attractive if you truly believe the product quality is high.",
    opponent: "Buyer",
    rows: ["No Warranty", "Standard Warranty", "Strong Warranty"],
    cols: ["Ignore", "Investigate", "Buy Now"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "vc-due-diligence-signal",
    type: "matrix",
    title: "VC Due Diligence Signal",
    category: "Signaling",
    concept: "Costly Commitment",
    situation:
      "You are raising a seed round and deciding how much traction evidence to present. You can show a light pitch, a rigorous data room, or an expensive all-out signal like major audits and enterprise pilots. The investor can pass, diligence, or term-sheet quickly.",
    opponent: "VC Partner",
    rows: ["Light Pitch", "Rigorous Data Room", "All-Out Signal"],
    cols: ["Pass", "Diligence", "Fast Term Sheet"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "esg-disclosure-package",
    type: "matrix",
    title: "ESG Disclosure Package",
    category: "Signaling",
    concept: "Credible Disclosure",
    situation:
      "You are preparing an ESG report for public investors. You can disclose very little, provide a balanced audited package, or overinvest in glossy signaling. Investors can discount it, study it, or price the stock as if credibility is already high.",
    opponent: "Public Investor",
    rows: ["Minimal Disclosure", "Audited Package", "Glossy Signal"],
    cols: ["Discount", "Study", "Trust Quickly"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "food-safety-certification",
    type: "matrix",
    title: "Food Safety Certification",
    category: "Signaling",
    concept: "Third-Party Verification",
    situation:
      "You run a food exporter and can offer no certification, a standard independent audit, or a very expensive premium certification. The foreign retailer can ignore you, evaluate carefully, or stock immediately. Certification is useful only if buyers trust the verification.",
    opponent: "Retail Buyer",
    rows: ["No Certification", "Standard Audit", "Premium Certification"],
    cols: ["Ignore", "Evaluate", "Stock Now"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "saas-uptime-signal",
    type: "matrix",
    title: "SaaS Uptime Signal",
    category: "Signaling",
    concept: "Reliability Signaling",
    situation:
      "You are selling enterprise software and can publish no uptime guarantee, a realistic SLA, or an extreme promise with heavy penalties. The client can pass, run a pilot, or sign immediately. Service guarantees reveal what you believe about your own reliability.",
    opponent: "Enterprise Client",
    rows: ["No SLA", "Realistic SLA", "Extreme SLA"],
    cols: ["Pass", "Pilot", "Sign Now"],
    payoffs: [
      [1, 2],
      [2, 3],
      [0, 1],
      [1, 1],
      [5, 5],
      [4, 3],
      [0, 0],
      [3, 2],
      [3, 4],
    ],
  },
  {
    id: "border-escalation-ladder",
    type: "matrix",
    title: "Border Escalation Ladder",
    category: "Int'l Relations",
    concept: "Calibrated Deterrence",
    situation:
      "You are responding to a tense border incident with a rival state. You can de-escalate, hold a visible defensive line, or escalate with offensive deployments. Each move affects both security and the risk of spiraling conflict.",
    opponent: "Rival State",
    rows: ["De-Escalate", "Hold Line", "Escalate"],
    cols: ["De-Escalate", "Hold Line", "Escalate"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "three-nation-deterrence-posture",
    type: "matrix",
    title: "Three-Nation Deterrence Posture",
    category: "Int'l Relations",
    concept: "Balancing Under Uncertainty",
    situation:
      "You are setting your military posture in a region where a third power could opportunistically react to whatever you and your main rival do. You can stay light, maintain a balanced deterrent, or surge forces. The problem is not just the rival's action, but what your action signals to everyone else watching.",
    opponent: "Primary Rival",
    rows: ["Light Posture", "Balanced Deterrent", "Force Surge"],
    cols: ["Light Posture", "Balanced Deterrent", "Force Surge"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "alliance-burden-sharing",
    type: "matrix",
    title: "Alliance Burden Sharing",
    category: "Int'l Relations",
    concept: "Arms-Race Externality",
    situation:
      "You and an ally are deciding whether to contribute little, contribute adequately, or surge defense spending far above the plan. Each side wants the alliance to look credible, but each also prefers the other to pay more. Extra spending can reassure partners while also provoking rivals.",
    opponent: "Alliance Partner",
    rows: ["Contribute Little", "Meet Target", "Surge Spending"],
    cols: ["Contribute Little", "Meet Target", "Surge Spending"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "naval-patrol-signaling",
    type: "matrix",
    title: "Naval Patrol Signaling",
    category: "Int'l Relations",
    concept: "Presence vs. Provocation",
    situation:
      "You are choosing the intensity of naval patrols in disputed waters. A low-profile patrol avoids friction, a regular patrol signals resolve, and a highly public patrol is maximally assertive. The other navy is deciding on the same ladder at the same time.",
    opponent: "Rival Navy",
    rows: ["Low-Profile Patrol", "Regular Patrol", "High-Visibility Patrol"],
    cols: ["Low-Profile Patrol", "Regular Patrol", "High-Visibility Patrol"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "missile-defense-deployment",
    type: "matrix",
    title: "Missile Defense Deployment",
    category: "Int'l Relations",
    concept: "Security Dilemma",
    situation:
      "You are choosing whether to deploy a limited, moderate, or expansive missile defense system. Your rival interprets each step as either defensive reassurance or offensive preparation. The more one side builds, the more the other side feels pushed to answer.",
    opponent: "Rival Power",
    rows: ["Limited Shield", "Moderate Shield", "Expansive Shield"],
    cols: ["Limited Shield", "Moderate Shield", "Expansive Shield"],
    payoffs: [
      [6, 6],
      [2, 8],
      [0, 9],
      [8, 2],
      [5, 5],
      [1, 7],
      [9, 0],
      [7, 1],
      [3, 3],
    ],
  },
  {
    id: "trade-pact-commitment",
    type: "matrix",
    title: "Trade Pact Commitment",
    category: "Int'l Relations",
    concept: "Credible Moderation",
    situation:
      "You are negotiating enforcement language for a new trade pact. You can insist on soft language, balanced enforcement, or maximal retaliation clauses. The other government is choosing the same tone, and both sides know that overly weak or overly harsh terms can unravel cooperation.",
    opponent: "Trade Partner",
    rows: ["Soft Terms", "Balanced Terms", "Harsh Terms"],
    cols: ["Soft Terms", "Balanced Terms", "Harsh Terms"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "climate-club-border-tariffs",
    type: "matrix",
    title: "Climate Club Border Tariffs",
    category: "Int'l Relations",
    concept: "Enforcement Coordination",
    situation:
      "You are deciding how hard to enforce a climate club with border tariffs on non-members. You can be lenient, balanced, or severe. The other club member is making the same choice, and inconsistent enforcement can destroy the credibility of the whole arrangement.",
    opponent: "Club Member",
    rows: ["Lenient Tariff", "Balanced Tariff", "Severe Tariff"],
    cols: ["Lenient Tariff", "Balanced Tariff", "Severe Tariff"],
    payoffs: [
      [4, 4],
      [2, 6],
      [0, 7],
      [6, 2],
      [5, 5],
      [3, 4],
      [7, 0],
      [4, 3],
      [1, 1],
    ],
  },
  {
    id: "public-charity-credit",
    type: "ultimatum",
    title: "Public Charity Credit",
    category: "Ultimatum",
    concept: "Audience Effects",
    situation:
      "You are dividing public credit for a charity drive with a local organizer. You keep whatever share of the 100-point recognition budget you do not offer them. Because the split will be visible to donors, rejection has a public dimension.",
    opponent: "Local Organizer",
    threshold: 35,
  },
  {
    id: "festival-ticket-dispute",
    type: "ultimatum",
    title: "Festival Ticket Dispute",
    category: "Ultimatum",
    concept: "Reference Points",
    situation:
      "You are offering compensation after accidentally reselling someone else's festival ticket. You choose how much of a 100-point compensation budget they get and keep the remainder. Their decision is shaped by what they feel they were originally promised.",
    opponent: "Ticket Holder",
    threshold: 39,
  },
  {
    id: "freelancer-rush-fee",
    type: "ultimatum",
    title: "Freelancer Rush Fee",
    category: "Ultimatum",
    concept: "Procedural Fairness",
    situation:
      "A freelancer saved your project with a last-minute rush job and you are now proposing the bonus split from a 100-point budget. You keep the rest for the agency. The freelancer cares about whether the process feels respectful, not just the number.",
    opponent: "Freelancer",
    threshold: 33,
  },
  {
    id: "group-project-credit",
    type: "ultimatum",
    title: "Group Project Credit",
    category: "Ultimatum",
    concept: "Status and Recognition",
    situation:
      "You are assigning final presentation credit with a classmate after a group project. You choose how many of 100 points of visible recognition they get and keep the rest. Because recognition affects reputation, the stakes are not purely monetary.",
    opponent: "Classmate",
    threshold: 41,
  },
  {
    id: "cross-border-vendor-bargain",
    type: "ultimatum",
    title: "Cross-Border Vendor Bargain",
    category: "Ultimatum",
    concept: "Cultural Norms",
    situation:
      "You are settling a dispute with an overseas vendor and proposing how to divide a 100-point compensation fund. You keep the remainder for your firm. What counts as acceptable is shaped by local business norms as well as the money itself.",
    opponent: "Vendor",
    threshold: 48,
  },
  {
    id: "airport-voucher-claim",
    type: "ultimatum",
    title: "Airport Voucher Claim",
    category: "Ultimatum",
    concept: "Time Pressure and Fatigue",
    situation:
      "You are an airline supervisor offering compensation to a stranded passenger at midnight. You propose how much of a 100-point voucher budget they receive and keep the rest in reserve. Exhaustion may soften demands a little, but not indefinitely.",
    opponent: "Stranded Passenger",
    threshold: 29,
  },
  {
    id: "union-shop-outside-option",
    type: "ultimatum",
    title: "Union Shop Outside Option",
    category: "Ultimatum",
    concept: "BATNA Strength",
    situation:
      "You are negotiating a one-time shop-floor bonus with a unionized crew. You decide how much of a 100-point pool workers get and keep the rest for management reserves. The crew can reject and lean on a credible outside option through formal grievance channels.",
    opponent: "Union Crew",
    threshold: 44,
  },
  {
    id: "supplier-renegotiation-round-two",
    type: "ultimatum",
    title: "Supplier Renegotiation Round Two",
    category: "Ultimatum",
    concept: "Multi-Round Ultimatum",
    situation:
      "You are renegotiating a supply contract after already having one tense round last month. You propose how much of a 100-point savings pool the supplier gets and keep the rest for your company. Past history shapes how they interpret today's offer.",
    opponent: "Supplier",
    threshold: 36,
  },
  {
    id: "security-deposit-return",
    type: "ultimatum",
    title: "Security Deposit Return",
    category: "Ultimatum",
    concept: "Entitlement Effects",
    situation:
      "You are returning a former tenant's security deposit and deciding the split after disputed repairs. You choose how much of 100 points they get back and keep the rest for claimed damage costs. They can reject and escalate because they feel the money is already theirs.",
    opponent: "Former Tenant",
    threshold: 41,
  },
  {
    id: "family-vineyard-inheritance",
    type: "centipede",
    title: "Family Vineyard Inheritance",
    category: "Centipede",
    concept: "Backward Induction vs. Legacy",
    situation:
      "You and a sibling are deciding when to cash out a family vineyard. Each time someone passes, the total legacy pot grows, but whoever takes first locks in a larger personal share immediately. Family trust pushes one way, backward induction pushes the other.",
    opponent: "Partner",
    nodes: 10,
    startPot: [5, 2],
    growth: 1.6,
    computer: "backward",
  },
  {
    id: "vc-bridge-round",
    type: "centipede",
    title: "VC Bridge Round",
    category: "Centipede",
    concept: "Trust in Sequential Investment",
    situation:
      "You and an investor are considering whether to keep extending a bridge round. Each pass grows the company valuation and future pot, but also gives the next mover a better opportunity to take. The tension is between patience and the fear of being the last cooperator.",
    opponent: "Partner",
    nodes: 12,
    startPot: [4, 2],
    growth: 1.7,
    computer: "cooperate",
  },
  {
    id: "arms-treaty-inspections",
    type: "centipede",
    title: "Arms Treaty Inspections",
    category: "Centipede",
    concept: "Backward Induction vs. Verification",
    situation:
      "You and a rival state are deciding whether to keep allowing deeper arms-control inspections. Each pass expands mutual security gains, but each side could take a short-term advantage by locking in early. Verification builds value, yet also creates temptation.",
    opponent: "Partner",
    nodes: 10,
    startPot: [3, 2],
    growth: 1.7,
    computer: "backward",
  },
  {
    id: "watershed-pollution-pact",
    type: "centipede",
    title: "Watershed Pollution Pact",
    category: "Centipede",
    concept: "Trust in Environmental Cooperation",
    situation:
      "You and a neighboring region can keep extending a watershed cleanup pact. Each pass grows the shared ecological gains, but the side that takes first secures a private budget advantage. The puzzle is whether long-term ecological trust can beat short-term fiscal temptation.",
    opponent: "Partner",
    nodes: 11,
    startPot: [4, 2],
    growth: 1.6,
    computer: "cooperate",
  },
  {
    id: "supplier-credit-terms",
    type: "centipede",
    title: "Supplier Credit Terms",
    category: "Centipede",
    concept: "Supply Chain Trust",
    situation:
      "You and a supplier are deciding whether to keep extending payment terms to grow a joint account. Every pass expands the account value, but also gives the next mover the chance to take a larger guaranteed share. Commercial trust creates value, but it is always vulnerable to one last opportunistic move.",
    opponent: "Partner",
    nodes: 8,
    startPot: [5, 2],
    growth: 1.5,
    computer: "cooperate",
  },
  {
    id: "academic-coauthor-project",
    type: "centipede",
    title: "Academic Coauthor Project",
    category: "Centipede",
    concept: "Collaboration vs. Credit Grabbing",
    situation:
      "You and a coauthor can keep revising a paper together, which grows the eventual publication payoff. At any point, one of you can stop and claim the current draft credit. The longer you collaborate, the better the paper gets, but the more tempting it becomes to take the existing gains.",
    opponent: "Partner",
    nodes: 12,
    startPot: [3, 3],
    growth: 1.6,
    computer: "cooperate",
  },
  {
    id: "coalition-cabinet-bargain",
    type: "centipede",
    title: "Coalition Cabinet Bargain",
    category: "Centipede",
    concept: "Sequential Trust in Politics",
    situation:
      "You and a coalition partner are deciding whether to keep bargaining over cabinet concessions. Each pass expands the total coalition surplus, but whoever takes first locks in a personal share and ends the sequence. Political patience can create a stronger government, but mistrust can end the game early.",
    opponent: "Partner",
    nodes: 9,
    startPot: [4, 1],
    growth: 1.7,
    computer: "backward",
  },
  {
    id: "startup-equity-vesting",
    type: "centipede",
    title: "Startup Equity Vesting",
    category: "Centipede",
    concept: "Sequential Commitment",
    situation:
      "You and a cofounder can keep extending vesting milestones that grow the value of the company. Each pass increases the pie, but also hands the next player a larger take-now option. Equity structures are designed precisely because trust alone is brittle.",
    opponent: "Partner",
    nodes: 14,
    startPot: [3, 1],
    growth: 1.7,
    computer: "cooperate",
  },
  {
    id: "open-source-maintainer-trust",
    type: "centipede",
    title: "Open-Source Maintainer Trust",
    category: "Centipede",
    concept: "Reciprocity in Volunteer Work",
    situation:
      "You and another maintainer can keep contributing to a shared open-source tool. Each pass grows adoption and reputation for both of you, but either maintainer can stop and cash in the current prestige. Volunteer systems work only if enough players resist the urge to capture value too early.",
    opponent: "Partner",
    nodes: 10,
    startPot: [2, 2],
    growth: 1.8,
    computer: "cooperate",
  },
  {
    id: "pharma-co-development",
    type: "centipede",
    title: "Pharma Co-Development",
    category: "Centipede",
    concept: "Milestone Trust",
    situation:
      "You and a biotech partner can keep funding shared milestones on a drug candidate. Every pass increases the program's value, but also lets the next player lock in a larger private claim. Joint innovation benefits from patience, but milestone cliffs create strong incentives to stop first.",
    opponent: "Partner",
    nodes: 11,
    startPot: [4, 2],
    growth: 1.6,
    computer: "backward",
  },
  {
    id: "local-climate-adaptation-fund",
    type: "centipede",
    title: "Local Climate Adaptation Fund",
    category: "Centipede",
    concept: "Sequential Public Investment",
    situation:
      "You and a neighboring city can keep rolling money into a shared adaptation fund. Each pass grows the total resilience payoff, but whichever side takes first secures a bigger immediate local share. The question is whether mutual exposure to climate risk is enough to sustain cooperation.",
    opponent: "Partner",
    nodes: 13,
    startPot: [3, 2],
    growth: 1.6,
    computer: "cooperate",
  },
  {
    id: "media-licensing-partnership",
    type: "centipede",
    title: "Media Licensing Partnership",
    category: "Centipede",
    concept: "Relationship Value",
    situation:
      "You and a streaming partner can keep extending a licensing relationship to grow a catalogue. Each pass expands the eventual pot, but also leaves the next mover holding a better take-now option. Relationships with strong future value often look more cooperative than the formal model predicts.",
    opponent: "Partner",
    nodes: 8,
    startPot: [4, 3],
    growth: 1.5,
    computer: "cooperate",
  },
  {
    id: "peacekeeping-burden-sharing",
    type: "centipede",
    title: "Peacekeeping Burden Sharing",
    category: "Centipede",
    concept: "Sequential Cooperation",
    situation:
      "You and an allied government are deciding whether to keep increasing support for a peacekeeping mission. Each pass enlarges the mission's success payoff, but the next mover can always stop and preserve more resources at home. Shared goals raise the value of patience, but domestic politics reward early taking.",
    opponent: "Partner",
    nodes: 12,
    startPot: [3, 1],
    growth: 1.7,
    computer: "backward",
  },
  {
    id: "co-manufacturing-partnership",
    type: "centipede",
    title: "Co-Manufacturing Partnership",
    category: "Centipede",
    concept: "Business Partnership Trust",
    situation:
      "You and a manufacturing partner can keep investing in joint process improvements. Each pass makes the factory more productive, but also increases the prize available to whoever pulls out first. The game asks whether trust in a business partnership can outrun the temptation to secure today's gains.",
    opponent: "Partner",
    nodes: 9,
    startPot: [5, 1],
    growth: 1.7,
    computer: "cooperate",
  },
  {
    id: "neighborhood-watch-reciprocity",
    type: "repeated",
    title: "Neighborhood Watch Reciprocity",
    category: "Repeated PD",
    concept: "Tit-for-Tat",
    situation:
      "You and a neighbor decide each week whether to patrol the block or skip your turn. The neighbor starts cooperative and then mirrors what you did last round. A small reciprocal strategy can sustain a lot of trust if you do not break it first.",
    opponent: "Neighbor",
    strategy: "tit-for-tat",
    rounds: 10,
  },
  {
    id: "joint-venture-compliance",
    type: "repeated",
    title: "Joint Venture Compliance",
    category: "Repeated PD",
    concept: "Grim Trigger",
    situation:
      "You and a partner must decide each month whether to honor a costly compliance standard. Your partner cooperates until you defect once; after that, they defect forever. The threat is harsh, but it can keep both sides disciplined.",
    opponent: "Joint Venture Partner",
    strategy: "grim-trigger",
    rounds: 12,
  },
  {
    id: "one-off-outsourcing-trap",
    type: "repeated",
    title: "One-Off Outsourcing Trap",
    category: "Repeated PD",
    concept: "Always Defect",
    situation:
      "You are working with a procurement broker who chases the best short-run deal every single round. They never reward your cooperation and never forgive your trust. This is what repeated interaction looks like when the opponent simply exploits every opening.",
    opponent: "Broker",
    strategy: "always-defect",
    rounds: 8,
  },
  {
    id: "open-source-goodwill",
    type: "repeated",
    title: "Open-Source Goodwill",
    category: "Repeated PD",
    concept: "Always Cooperate",
    situation:
      "You are working with an open-source contributor who keeps sharing fixes regardless of what you do. Every round, they cooperate again. This lets you see both how generosity creates value and how easily pure niceness can be exploited.",
    opponent: "Volunteer Maintainer",
    strategy: "always-cooperate",
    rounds: 8,
  },
  {
    id: "customer-service-partnership",
    type: "repeated",
    title: "Customer Service Partnership",
    category: "Repeated PD",
    concept: "Generous Tit-for-Tat",
    situation:
      "You and a service partner decide whether to absorb small customer issues or push costs onto the other side. Your partner usually reciprocates your last move, but sometimes forgives a single defection and tries cooperation again. That forgiveness can save the relationship when frictions are small.",
    opponent: "Service Partner",
    strategy: "generous-tit-for-tat",
    rounds: 10,
  },
  {
    id: "harbor-fisheries-patrol",
    type: "repeated",
    title: "Harbor Fisheries Patrol",
    category: "Repeated PD",
    concept: "Win-Stay-Lose-Shift",
    situation:
      "You and another fishing crew decide whether to respect the harbor quota or overfish. Your rival repeats a move that worked last round and switches after a bad outcome. This simple adaptive rule can do surprisingly well without complex foresight.",
    opponent: "Rival Crew",
    strategy: "win-stay-lose-shift",
    rounds: 10,
  },
  {
    id: "border-cyber-noise",
    type: "repeated",
    title: "Border Cyber Noise",
    category: "Repeated PD",
    concept: "Random",
    situation:
      "You and another cyber team can respect a quiet norm or launch a probe each round. The other side behaves unpredictably, sometimes cooperating and sometimes defecting with no stable pattern. That randomness makes reputation almost impossible to read.",
    opponent: "Cyber Team",
    strategy: "random",
    rounds: 10,
  },
  {
    id: "sibling-business-lenience",
    type: "repeated",
    title: "Sibling Business Lenience",
    category: "Repeated PD",
    concept: "Tit-for-Two-Tats",
    situation:
      "You and a sibling share a family business and decide whether to cover for each other's short-term cash needs. Your sibling tolerates one bad round but retaliates only after two consecutive defections. That extra patience can prevent overreaction to one-off problems.",
    opponent: "Sibling",
    strategy: "tit-for-two-tats",
    rounds: 10,
  },
  {
    id: "long-term-supplier-contract",
    type: "repeated",
    title: "Long-Term Supplier Contract",
    category: "Repeated PD",
    concept: "Shadow of the Future",
    situation:
      "You and a supplier decide each quarter whether to honor a costly quality standard. Because the contract is expected to run for years, every short-run gain from cheating has to be weighed against a long future of retaliation. The future makes today's choice heavier.",
    opponent: "Supplier",
    strategy: "tit-for-tat",
    rounds: 16,
  },
  {
    id: "community-solar-maintenance",
    type: "repeated",
    title: "Community Solar Maintenance",
    category: "Repeated PD",
    concept: "Shadow of the Future",
    situation:
      "You and another building manager decide whether to contribute to shared solar maintenance each season. The project will keep running for a long time, so cutting corners today risks many future bad rounds. Long horizons make reciprocity more powerful.",
    opponent: "Building Manager",
    strategy: "tit-for-tat",
    rounds: 14,
  },
  {
    id: "scientific-data-sharing-network",
    type: "repeated",
    title: "Scientific Data-Sharing Network",
    category: "Repeated PD",
    concept: "Shadow of the Future",
    situation:
      "You and another lab decide whether to share data before publication. Future grants, coauthorships, and access all depend on whether the relationship survives beyond this paper. The repeated nature of science can make cooperation rational, not just altruistic.",
    opponent: "Other Lab",
    strategy: "generous-tit-for-tat",
    rounds: 15,
  },
  {
    id: "regional-water-board",
    type: "repeated",
    title: "Regional Water Board",
    category: "Repeated PD",
    concept: "Shadow of the Future",
    situation:
      "You and a neighboring district decide each month whether to conserve water or overdraw from a shared basin. The drought will last for years, so every move affects the next season too. Long horizons turn local restraint into a strategic investment.",
    opponent: "Neighboring District",
    strategy: "grim-trigger",
    rounds: 15,
  },
  {
    id: "apartment-building-quiet-hours",
    type: "repeated",
    title: "Apartment Building Quiet Hours",
    category: "Repeated PD",
    concept: "Shadow of the Future",
    situation:
      "You and a neighbor decide each weekend whether to respect quiet hours or throw a loud party. You expect to live next to each other for a long time, so revenge and reconciliation both matter. Future contact changes how attractive a one-night defection really is.",
    opponent: "Neighbor",
    strategy: "win-stay-lose-shift",
    rounds: 13,
  },
  {
    id: "end-of-quarter-vendor-sprint",
    type: "repeated",
    title: "End-of-Quarter Vendor Sprint",
    category: "Repeated PD",
    concept: "Finite Horizon",
    situation:
      "You and a vendor decide for the last few weeks of a contract whether to honor service levels or cut corners. Everyone knows the relationship ends soon. The shrinking future makes late-round defection more tempting.",
    opponent: "Vendor",
    strategy: "tit-for-tat",
    rounds: 6,
  },
  {
    id: "semester-end-study-partnership",
    type: "repeated",
    title: "Semester-End Study Partnership",
    category: "Repeated PD",
    concept: "Finite Horizon",
    situation:
      "You and a classmate decide whether to share notes for the last few weeks before finals. Because the course ends soon, there are only a handful of rounds left. Endgames change behavior even when trust was strong earlier.",
    opponent: "Classmate",
    strategy: "tit-for-two-tats",
    rounds: 5,
  },
  {
    id: "campaign-coalition-countdown",
    type: "repeated",
    title: "Campaign Coalition Countdown",
    category: "Repeated PD",
    concept: "Finite Horizon",
    situation:
      "You and a coalition ally decide whether to share volunteers during the final weeks of an election. The alliance has a clear expiration date on election day. As the deadline nears, the value of maintaining trust falls.",
    opponent: "Coalition Ally",
    strategy: "grim-trigger",
    rounds: 7,
  },
  {
    id: "open-ended-franchise-relationship",
    type: "repeated",
    title: "Open-Ended Franchise Relationship",
    category: "Repeated PD",
    concept: "Infinite Horizon Intuition",
    situation:
      "You and a franchise partner decide each month whether to keep quality high or quietly cut costs. There is no clear end date to the relationship. When the horizon feels open-ended, defection today can poison a very long future.",
    opponent: "Franchise Partner",
    strategy: "tit-for-tat",
    rounds: 18,
  },
  {
    id: "renewable-power-purchase-renewal",
    type: "repeated",
    title: "Renewable Power Purchase Renewal",
    category: "Repeated PD",
    concept: "Infinite Horizon Intuition",
    situation:
      "You and a utility counterpart decide whether to share short-term cost savings or honor a clean-energy purchasing pact. The contract is expected to roll over repeatedly. An indefinite relationship makes preserving trust strategically valuable.",
    opponent: "Utility Counterpart",
    strategy: "generous-tit-for-tat",
    rounds: 18,
  },
  {
    id: "consulting-team-email-misfire",
    type: "repeated",
    title: "Consulting Team Email Misfire",
    category: "Repeated PD",
    concept: "Noise and Forgiveness",
    situation:
      "You and another consultant decide whether to share leads or hold them back, but sometimes an email gets missed and cooperation looks like defection. Small misunderstandings can trigger retaliation if neither side is forgiving. In noisy environments, intentions are harder to read than actions.",
    opponent: "Consulting Partner",
    strategy: "generous-tit-for-tat",
    rounds: 12,
  },
  {
    id: "harbor-sensor-glitch",
    type: "repeated",
    title: "Harbor Sensor Glitch",
    category: "Repeated PD",
    concept: "Noise and Forgiveness",
    situation:
      "You and another harbor crew decide whether to obey a catch limit, but the monitoring sensor sometimes flags a compliant boat as cheating. A harsh response to every signal can destroy trust. The challenge is telling true defection from bad data.",
    opponent: "Other Crew",
    strategy: "tit-for-two-tats",
    rounds: 12,
  },
  {
    id: "payment-processing-glitch",
    type: "repeated",
    title: "Payment Processing Glitch",
    category: "Repeated PD",
    concept: "Noise and Forgiveness",
    situation:
      "You and a small supplier decide whether to ship early or hold back, but a payment processor sometimes delays transfers and makes cooperation look one-sided. The supplier follows an unforgiving rule. A single mistaken signal can poison the whole relationship.",
    opponent: "Supplier",
    strategy: "grim-trigger",
    rounds: 10,
  },
  {
    id: "hospital-handoff-miscommunication",
    type: "repeated",
    title: "Hospital Handoff Miscommunication",
    category: "Repeated PD",
    concept: "Noise and Forgiveness",
    situation:
      "You and another clinician decide whether to do full handoff notes or minimal notes, but sometimes the charting system hides a careful note. The other side adapts based on whether the last round seemed to work. Miscommunication turns strategy into diagnosis.",
    opponent: "Clinician",
    strategy: "win-stay-lose-shift",
    rounds: 11,
  },
  {
    id: "border-radar-false-alarm",
    type: "repeated",
    title: "Border Radar False Alarm",
    category: "Repeated PD",
    concept: "Noise and Forgiveness",
    situation:
      "You and a neighboring patrol decide whether to respect a demilitarized line, but false radar alarms sometimes make restraint look like aggression. The other side is mostly reciprocal and occasionally forgiving. That forgiveness is often what keeps a single sensor error from escalating into a norm collapse.",
    opponent: "Border Patrol",
    strategy: "generous-tit-for-tat",
    rounds: 13,
  },
  {
    id: "freelance-marketplace-reviews",
    type: "repeated",
    title: "Freelance Marketplace Reviews",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and a client decide whether to be fair on a freelance platform. Everyone can see ratings from earlier deals, so one bad round affects future partners too. Reputation extends the game beyond the person directly in front of you.",
    opponent: "Marketplace Client",
    strategy: "tit-for-tat",
    rounds: 10,
  },
  {
    id: "vendor-reputation-network",
    type: "repeated",
    title: "Vendor Reputation Network",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and a retailer decide whether to honor rush commitments, knowing that trade references circulate across the whole network. A defection against one partner may poison several future deals. Reputation makes repeated games social rather than purely bilateral.",
    opponent: "Retailer",
    strategy: "grim-trigger",
    rounds: 11,
  },
  {
    id: "village-credit-circle",
    type: "repeated",
    title: "Village Credit Circle",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and another member of a village credit circle decide whether to repay on time or delay. Everyone in the group hears about late behavior. The community remembers much longer than one bilateral interaction would.",
    opponent: "Credit Circle Member",
    strategy: "generous-tit-for-tat",
    rounds: 12,
  },
  {
    id: "airline-alliance-codeshare",
    type: "repeated",
    title: "Airline Alliance Codeshare",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and another airline decide whether to honor codeshare quality commitments. Alliance partners talk to one another, so cheating one route can hurt you in several negotiations. Cooperation is protected by the knowledge that others are watching.",
    opponent: "Alliance Airline",
    strategy: "win-stay-lose-shift",
    rounds: 12,
  },
  {
    id: "open-source-maintainer-reputation",
    type: "repeated",
    title: "Open-Source Maintainer Reputation",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and another maintainer decide whether to review each other's code carefully or push work back. The whole contributor community can see who behaves cooperatively. Future collaborators respond to that record, not just to your words.",
    opponent: "Maintainer",
    strategy: "tit-for-two-tats",
    rounds: 11,
  },
  {
    id: "restaurant-supplier-circuit",
    type: "repeated",
    title: "Restaurant Supplier Circuit",
    category: "Repeated PD",
    concept: "Group Reputation",
    situation:
      "You and a produce supplier decide whether to absorb small shocks or opportunistically squeeze the other side. Word travels quickly among restaurants and vendors in the district. One bad round can follow you into deals you have not yet signed.",
    opponent: "Produce Supplier",
    strategy: "tit-for-tat",
    rounds: 10,
  },
  {
    id: "pre-game-sales-handshake",
    type: "repeated",
    title: "Pre-Game Sales Handshake",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "Before repeated sales interactions begin, you and a distributor make a nonbinding promise to share leads fairly. Nothing legally forces either side to keep the promise. Even cheap talk can still matter if it coordinates expectations.",
    opponent: "Distributor",
    strategy: "tit-for-tat",
    rounds: 10,
  },
  {
    id: "climate-club-pledge-meeting",
    type: "repeated",
    title: "Climate Club Pledge Meeting",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "You and another minister publicly promise to maintain climate targets before repeated compliance decisions begin. The promise is not binding, but it creates a focal expectation. Words alone do not solve the game, yet they can move the starting point.",
    opponent: "Other Minister",
    strategy: "grim-trigger",
    rounds: 12,
  },
  {
    id: "factory-shift-break-room-pact",
    type: "repeated",
    title: "Factory Shift Break-Room Pact",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "You and another supervisor agree informally to cover each other's staffing gaps. The agreement has no formal enforcement, but both sides have now explicitly said they intend to cooperate. That conversation can make later defections feel more like betrayals than mere strategy.",
    opponent: "Supervisor",
    strategy: "win-stay-lose-shift",
    rounds: 11,
  },
  {
    id: "roommate-chore-agreement",
    type: "repeated",
    title: "Roommate Chore Agreement",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "You and a roommate agree at the kitchen table to split chores fairly over the next month. The agreement is not enforceable, but it helps define what each side expects. Clear cheap talk can be enough to get cooperation started.",
    opponent: "Roommate",
    strategy: "generous-tit-for-tat",
    rounds: 9,
  },
  {
    id: "ceo-summit-nonbinding-pledge",
    type: "repeated",
    title: "CEO Summit Nonbinding Pledge",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "You and a rival CEO publicly say you want stable standards before repeated industry decisions begin. The pledge changes no formal incentives, but it broadcasts intent and raises the reputational cost of immediate cheating. Words can matter even when they are not contracts.",
    opponent: "Rival CEO",
    strategy: "tit-for-two-tats",
    rounds: 10,
  },
  {
    id: "team-captain-locker-room-talk",
    type: "repeated",
    title: "Team Captain Locker-Room Talk",
    category: "Repeated PD",
    concept: "Communication and Cheap Talk",
    situation:
      "You and another captain tell your teams you will both play unselfishly over the season. No rule forces that promise, but the declaration shapes how later actions are judged. Public communication changes beliefs and norms even when it changes no payoff cell directly.",
    opponent: "Other Captain",
    strategy: "tit-for-tat",
    rounds: 12,
  },
];
